// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb0DWHnCSdLD7Ywtq-9miG0Eo5IKytHZ4',
    appId: '1:157094344531:web:86eac8de5969f461ba13a6',
    messagingSenderId: '157094344531',
    projectId: 'fluter-test-bc01a',
    authDomain: 'fluter-test-bc01a.firebaseapp.com',
    storageBucket: 'fluter-test-bc01a.firebasestorage.app',
    measurementId: 'G-01SBD27N6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj_hVxgfCKQvtDk4SvZl0g7sZWSqrQOTQ',
    appId: '1:157094344531:android:daf621b039740f11ba13a6',
    messagingSenderId: '157094344531',
    projectId: 'fluter-test-bc01a',
    storageBucket: 'fluter-test-bc01a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO16YM8p-U4PYPykQVdDNieBrEoWtHEao',
    appId: '1:157094344531:ios:056343dbed81980fba13a6',
    messagingSenderId: '157094344531',
    projectId: 'fluter-test-bc01a',
    storageBucket: 'fluter-test-bc01a.firebasestorage.app',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb0DWHnCSdLD7Ywtq-9miG0Eo5IKytHZ4',
    appId: '1:157094344531:web:85068bc9106f931fba13a6',
    messagingSenderId: '157094344531',
    projectId: 'fluter-test-bc01a',
    authDomain: 'fluter-test-bc01a.firebaseapp.com',
    storageBucket: 'fluter-test-bc01a.firebasestorage.app',
    measurementId: 'G-RGG63M1F1W',
  );
}
